### ISSUE TITLE
Change authorization header on GET requests

### ISSUE THREAD

**Issue by RealCerus** [VirtualSped/backend#1]
Problem:
Because the C# Http request api is shit the normal `Authorization` header gets removed when sending a GET request.

Solution:
Change the Authorization header to something like "Auth" or "VSped-Auth" or something along those lines

**Comment by Lukaesebrot** [comment]
No, because I don't want that messy code. The Authorization header exists for exactly that case and I don't see any fact that would lead me to change it. I am sure that there is a solution how to send this header using C#.
