### ISSUE TITLE
[Bug] Server responds with 422 when viewing company

### ISSUE THREAD

**Issue by RealCerus** [VirtualSped/backend#3]
**Description:**
While testing the /company/create and /company/view endpoint I encountered that the server responds with a 422 error when trying to view the company of the token owner.

**Steps to reproduce:**
1. Create company through `/company/create` endpoint
2. Try to view company through `/company/view` endpoint without the `companyID` query parameter

**Relevant code pieces / errors:**
[VSpedApi.cs](https://pastebin.com/ytrRgVMQ)
[Tests.cs](https://pastebin.com/jrrF4w2S)
[Error](http://lightshot.cerus-dev.de/file//f0c7af302e5f428ea8c5f689e9ba4484)

**Comment by Lukaesebrot** [comment]
As described in #4 I will restructure some endpoints and logical things. I will respect this bug then.
