### ISSUE TITLE
[Suggestion] Implement endpoints to list applications and members of a company

### ISSUE THREAD

**Issue by RealCerus** [VirtualSped/backend#4]
**Description:**
Implement endpoints for the following things:
- Members of a company
- Applications of a company

**Implementation:**
### Members of a company
Path: /company/members
Required parameters: `companyID` query parameter
Returns: Json formatted response (Like `{"members":[{"id":"xxx","name":"xxx","role":"xxx"}]}`)

### Applications of / to a company
Path: /company/applications
Required parameters: `companyID` query parameter, `Authorization` header (High role required to use this endpoint)
Returns: Json formatted response (Like `{"applications":[{"id":"xxx","status":0}]}` (0 = Open, 1 = Accepted, 2 = Denied))

**Comment by Lukaesebrot** [comment]
I'm going to restructure some endpoints anyways so this will get implemented.
